name: Copy Repository to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Compress repository folder
        run: zip -r repo.zip src

      - name: Copy zip file to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: repo.zip
          target: /home/ubuntu/hello-node
            
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 16.170.37.57 >> ~/.ssh/authorized_keys

      - name: Execute script on remote EC2
        run: |
          ssh -i ~/.ssh/id_rsa root@16.170.37.57 'bash -s' < /unzip-file.sh
      
